name: elements
version: 1.0.3
author: Patrick Minogue <patrick.minogue@appfoundry.se>
description: A library with different custom elements
homepage: https://github.com/afpatmin/elements

environment:
  sdk: '>=2.0.0 <3.0.0'
